### ISSUE TITLE
better to support more permitted_characters(like :~-;/}'<>) and support some other reverse bytes？

### ISSUE THREAD

**Issue by iromise** [theonlypwner/crc32#1]
There may be some file(3 bytes or 4 bytes or 5 bytes) zipped with some password(contains not only alphanumeric), may be it is better to support these conditions?
since I am not familiar with your code, maybe I could not give a pull request for now.

**Comment by theonlypwner** [comment]
This project does not crack ZIP passwords. It just generates patch bytes that could be appended to force the CRC32 checksum to a certain value.
