### ISSUE TITLE
Show ASCII text for 4-byte patches

### ISSUE THREAD

**Issue by tysmlq** [theonlypwner/crc32#2]
this crc32.py could solve 6 bytes crc32 value well,but couldn't solve 4 bytes value,how can do it by crc32.py?

**Comment by theonlypwner** [comment]
My program solves both 6-byte "alphanumeric plus underscore" and 4-byte patches.

Do you have more information?

**Comment by tysmlq** [comment]
thank you for your reply!
I found it perhaps exist some problem when decode 4-byte clear text,such as "pass,pher,the_,word",but these words can decode by the other script,just like below.
pass -> -0x318f2bdc
pher -> -0x55c19516
the_  -> 0x6083a1c8
word -> -0x3c0e8aef

**Comment by theonlypwner** [comment]
I'll add something to show the 4 bytes as text when all bytes are in `permitted_characters`.

I originally didn't add this, since I expected the 4-byte patch CRC32 to have non-permitted characters most of the time.
